### ISSUE TITLE
Error occurs if the file name to be loaded by avs contains Japanese characters.

### ISSUE THREAD

**Issue by buccimoni** [msg7086/x265-Yuuki-Asuna#20] opened 2021-06-04 10:22 UTC
I'm currently using "x265-Asuna-3.4+13-g729a838d3+38".
I'm using "x265-Asuna-3.4+13-g729a838d3+38" to encode the avs file directly.
If I do the same and change the binary to "x265-Yuuki-3.5+2-g2b25c9ba0+45", I get an error.

--- error begin
.\bin\x265-Yuuki-3.5-gcc-10-lite.exe --input .\demux_Plus.avs --output test.265
avs+ [info]: AviSynth+ 3.7.0 (r3382, 3.7, x86_64)
avs+ [error]: Error loading file: MPEG2Source: Could not open one of the input files.
(.\demux_Plus.avs, line 52)
x265 [error]: unable to open input file <.\demux_Plus.avs>
--- error end

I am using MPEG2Source() in the avs file to load the d2v file, and the cause seems to be the presence of Japanese in the name of the source file described in the d2v file.
If you use only alphabetic file names, the error does not occur and the encoding can be done normally.

If possible, I would like to pass avs directly like x265-Asuna to encode the file.

**Comment by buccimoni** [comment] 2021-06-05 16:40
Additional Notes.
If the character encoding of the d2v file output by DGIndex is SJIS, AviSynth+ outputs an error on x265-Yuuki, but not on x265-Asuna 3.4.
If you convert the d2v file to UTF-8, it will be encoded correctly.
However, the tool I'm running at the same time doesn't seem to work unless the d2v file is in SJIS.
It would be nice if x265-Yuuki 3.5 could also handle SJIS.

**Comment by msg7086** [comment] 2021-06-05 20:18
Sounds like a missing patch on Yuuki branch. I'll check when I have time.

**Comment by tana3n** [comment] 2021-08-27 06:26
I tried it, and it seems to be caused by this commit(b5a411d52ce086cdcd2d38f38d47c666598d5ba7).

The same thing seems to be reported with x264(in Japanese diary).
[x264 UTF\-8になったとかそんなところのメモ \- \.\.たれろぐ\.\.](https://naga-sawa.hatenadiary.org/entry/2021/02/11/134654)
This seems to occur in non-UTF-8 environments.

When I checked, changing from UTF-8 to Shift-JIS in the activeCodePage of x265res.manifest.in improved the problem.
However, other problems may occur.
It's not bad for individuals to build and use, but I don't know if it should be merged considering the UTF-8 environment.

**Comment by buccimoni** [comment] 2021-08-27 12:27
> 
> 
> I tried it, and it seems to be caused by this commit([b5a411d](https://github.com/msg7086/x265-Yuuki-Asuna/commit/b5a411d52ce086cdcd2d38f38d47c666598d5ba7)).
> 
> The same thing seems to be reported with x264(in Japanese diary).
> [x264 UTF-8になったとかそんなところのメモ - ..たれろぐ..](https://naga-sawa.hatenadiary.org/entry/2021/02/11/134654)
> This seems to occur in non-UTF-8 environments.
> 
> When I checked, changing from UTF-8 to Shift-JIS in the activeCodePage of x265res.manifest.in improved the problem.
> However, other problems may occur.
> It's not bad for individuals to build and use, but I don't know if it should be merged considering the UTF-8 environment.

Thank you very much for your kind information.
When the activeCodePage part was corrected to Shift-JIS and the build was performed, the operation as expected could be performed.
Although this is contrary to the trend toward UTF-8, I personally would like to use the one I built myself.

**Comment by msg7086** [comment] 2021-08-29 05:25
https://down.7086.in/x265-Yuuki-Asuna/x265-gcc-multilib-full-ansi-test.7z Can you please try this version?

**Comment by buccimoni** [comment] 2021-08-29 08:43
> https://down.7086.in/x265-Yuuki-Asuna/x265-gcc-multilib-full-ansi-test.7z Can you please try this version?

I tried x265-gcc-multilib-full-ansi-test.7z and was able to encode successfully on Windows 10 Shift-JIS environment.
My build is working, but I would like to use this binary.
Many thanks!

**Comment by msg7086** [comment] 2021-08-29 09:06
大丈夫そうですね。今後はANSIバージョンもいれます。

**Closed as completed by msg7086** 2021-08-29 09:06 UTC
